services:
  - type: web
    name: kintsugi-backend
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: SECRET_KEY
        scope: build
        value: your-secret-key-here
      - key: ALLOWED_ORIGINS
        value: https://express-js-on-vercel-agp6.vercel.app,https://kintsugi-backend.onrender.com
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
